# Generated by Django 4.2.6 on 2023-10-29 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review_return', '0003_giveback_review_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='giveback',
            name='date_added',
        ),
    ]
