# Generated by Django 4.2.6 on 2023-10-25 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0004_rename_publisher_book_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='img_url',
            field=models.TextField(default='https://books.google.com/books/content?id=SXGCEAAAQBAJ&printsec=frontcover&img=1&zoom=5&edge=curl&source=gbs_api'),
        ),
    ]
