# Generated by Django 4.2.6 on 2023-10-28 00:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0006_book_favorited'),
        ('catalogue', '0006_book_last_edited_user'),
    ]

    operations = [
    ]
