# Generated by Django 4.2.6 on 2023-10-25 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('borrow', '0004_request'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='name',
        ),
    ]
