# Generated by Django 4.2.6 on 2023-10-15 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('borrow', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loan',
            name='masuk_cart',
        ),
    ]
