# Generated by Django 4.2.6 on 2023-10-15 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0003_alter_book_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='publisher',
            new_name='author',
        ),
    ]
