# Generated by Django 4.2.4 on 2023-10-26 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0005_book_img_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='favorited',
            field=models.BooleanField(default=False),
        ),
    ]
